//
// Generated by Bluespec Compiler, version 2026.01-54-ge8b70f8c (build e8b70f8c)
//
// On Thu May 21 08:15:14 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// value                          O     8 reg
// RDY_value                      O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkSimpleRegConflict(CLK,
			   RST_N,

			   value,
			   RDY_value);
  input  CLK;
  input  RST_N;

  // value method value
  output [7 : 0] value;
  output RDY_value;

  // signals for module outputs
  wire [7 : 0] value;
  wire RDY_value;

  // register r
  reg [7 : 0] r;
  wire [7 : 0] r$D_IN;
  wire r$EN;

  // value method value
  assign value = r ;
  assign RDY_value = 1'd1 ;

  // register r
  assign r$D_IN = 8'h55 ;
  assign r$EN = 1'b1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        r <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (r$EN) r <= `BSV_ASSIGNMENT_DELAY r$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    r = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkSimpleRegConflict

