//
// Generated by Bluespec Compiler, version 2026.01-54-ge8b70f8c (build e8b70f8c)
//
// On Thu May 21 08:15:15 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_enq                        O     1 reg
// RDY_deq                        O     1 reg
// first                          O     8 reg
// RDY_first                      O     1 reg
// notEmpty                       O     1 reg
// RDY_notEmpty                   O     1 const
// notFull                        O     1 reg
// RDY_notFull                    O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// enq_x                          I     8 reg
// EN_enq                         I     1
// EN_deq                         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkPipelineFIFO(CLK,
		      RST_N,

		      enq_x,
		      EN_enq,
		      RDY_enq,

		      EN_deq,
		      RDY_deq,

		      first,
		      RDY_first,

		      notEmpty,
		      RDY_notEmpty,

		      notFull,
		      RDY_notFull);
  input  CLK;
  input  RST_N;

  // action method enq
  input  [7 : 0] enq_x;
  input  EN_enq;
  output RDY_enq;

  // action method deq
  input  EN_deq;
  output RDY_deq;

  // value method first
  output [7 : 0] first;
  output RDY_first;

  // value method notEmpty
  output notEmpty;
  output RDY_notEmpty;

  // value method notFull
  output notFull;
  output RDY_notFull;

  // signals for module outputs
  wire [7 : 0] first;
  wire RDY_deq,
       RDY_enq,
       RDY_first,
       RDY_notEmpty,
       RDY_notFull,
       notEmpty,
       notFull;

  // ports of submodule fifo
  wire [7 : 0] fifo$D_IN, fifo$D_OUT;
  wire fifo$CLR, fifo$DEQ, fifo$EMPTY_N, fifo$ENQ, fifo$FULL_N;

  // action method enq
  assign RDY_enq = fifo$FULL_N ;

  // action method deq
  assign RDY_deq = fifo$EMPTY_N ;

  // value method first
  assign first = fifo$D_OUT ;
  assign RDY_first = fifo$EMPTY_N ;

  // value method notEmpty
  assign notEmpty = fifo$EMPTY_N ;
  assign RDY_notEmpty = 1'd1 ;

  // value method notFull
  assign notFull = fifo$FULL_N ;
  assign RDY_notFull = 1'd1 ;

  // submodule fifo
  FIFO2 #(.width(32'd8), .guarded(1'd1)) fifo(.RST(RST_N),
					      .CLK(CLK),
					      .D_IN(fifo$D_IN),
					      .ENQ(fifo$ENQ),
					      .DEQ(fifo$DEQ),
					      .CLR(fifo$CLR),
					      .D_OUT(fifo$D_OUT),
					      .FULL_N(fifo$FULL_N),
					      .EMPTY_N(fifo$EMPTY_N));

  // submodule fifo
  assign fifo$D_IN = enq_x ;
  assign fifo$ENQ = EN_enq ;
  assign fifo$DEQ = EN_deq ;
  assign fifo$CLR = 1'b0 ;
endmodule  // mkPipelineFIFO

