//
// Generated by Bluespec Compiler, version 2026.01-54-ge8b70f8c (build e8b70f8c)
//
// On Thu May 21 08:18:23 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_write                      O     1 const
// readOld                        O     8
// RDY_readOld                    O     1 const
// readNew                        O     8
// RDY_readNew                    O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// write_x                        I     8
// EN_write                       I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCRegBypass(CLK,
		    RST_N,

		    write_x,
		    EN_write,
		    RDY_write,

		    readOld,
		    RDY_readOld,

		    readNew,
		    RDY_readNew);
  input  CLK;
  input  RST_N;

  // action method write
  input  [7 : 0] write_x;
  input  EN_write;
  output RDY_write;

  // value method readOld
  output [7 : 0] readOld;
  output RDY_readOld;

  // value method readNew
  output [7 : 0] readNew;
  output RDY_readNew;

  // signals for module outputs
  wire [7 : 0] readNew, readOld;
  wire RDY_readNew, RDY_readOld, RDY_write;

  // inlined wires
  wire [7 : 0] r$port2__read;

  // register r
  reg [7 : 0] r;
  wire [7 : 0] r$D_IN;
  wire r$EN;

  // action method write
  assign RDY_write = 1'd1 ;

  // value method readOld
  assign readOld = r ;
  assign RDY_readOld = 1'd1 ;

  // value method readNew
  assign readNew = r ;
  assign RDY_readNew = 1'd1 ;

  // inlined wires
  assign r$port2__read = EN_write ? write_x : r ;

  // register r
  assign r$D_IN = r$port2__read ;
  assign r$EN = 1'b1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        r <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (r$EN) r <= `BSV_ASSIGNMENT_DELAY r$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    r = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCRegBypass

